name: Code verification

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        php: [7.2]
        # php: [7.2, 7.3, 7.4, 8.0]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP & Composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer:v2

    - name: Install dependencies
      run: composer install --no-interaction --no-suggest

    - name: Unit tests
      run: |
        mkdir -p build/logs
        ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

    - name: Static code analysis
      run: |
        ./vendor/bin/psalm --shepherd
    
    - name: Coveralls report
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        ./vendor/bin/php-coveralls -v
