name: Code verification

on: push

jobs:
  build:
    runs-on: ubuntu-20.04    

    strategy:
      matrix:
        php: [7.2, 7.3, 7.4, 8.0]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      uses: php-actions/composer@v5
      with:
        php_version: ${{ matrix.php }}
        version: 2
        args: --no-interaction
    
    - name: Unit tests
      run: |
        mkdir -p build/logs
        ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml  

    - name: Static code analysis
      run: |
        ./vendor/bin/psalm --shepherd
    
    - name: Coveralls report
      run: |
        ./vendor/bin/php-coveralls -v





